### ISSUE TITLE
A Sandbox for Kafka Connect Connectors Experimentation

### ISSUE THREAD

**Issue by estevaosaleme** [pmoskovi/kafka-learning-resources#2]
Name: A Sandbox for Kafka Connect Connectors Experimentation
Link: https://estevaosaleme.medium.com/a-sandbox-for-kafka-connect-connectors-experimentation-2e41f99aae15
Description: This article introduces a sandbox for Kafka Connect, an environment designed to simplify the process of testing different connectors. It enables developers to streamline their experimentation process, reducing the time spent on it.
Source: Estêvão Bissoli Saleme 
Skill Level: Intermediate
Resource Type: Guide or Tutorial, Blog Post
Interactivity: Hands-on Exercise
Language: Java, Other

**Comment by pmoskovi** [comment]
Thanks for submitting, @estevaosaleme! Nice blog post; it's now part of the list.

**Comment by estevaosaleme** [comment]
My pleasure! And again, brilliant repo. Thanks for this!
